### ISSUE TITLE
Truncate by word count instead of length

### ISSUE THREAD

**Issue by tunix** [evecalm/truncate-html#1]
Hi,

It'd be pretty nice to have this feature just like django's [truncatewords_html](https://docs.djangoproject.com/es/1.9/ref/templates/builtins/#truncatewords-html) feature.

**Comment by oe** [comment]
@tunix I'll try it sometime later

**Comment by claviska** [comment]
Willing to pay a bounty for this. 🤑

**Comment by oe** [comment]
😳  I'll work it out in these few days. Sorry for that

**Comment by claviska** [comment]
No worries, thanks for your efforts! Node needs a solid HTML truncate lib. Happy to help however possible!

**Comment by oe** [comment]
@tunix @claviska I've added an option `byWords`(default is `false`).  I haven't update it to NPM, you clone and test it. I will update NPM after complete test. Use it as follows:

```js
// with options, truncate by words. 
//  if you try to truncate none alphabet language(like CJK)
//      it will not act as you wish
var html = '<p><img src="abc.png">This is a string</p> for test.';
truncate(html, 3, {byWords: true});
// returns: <p><img src="abc.png">This is a ...</p>
```

**Comment by claviska** [comment]
Beautiful!

I'm testing this now and I can't seem to break it. The lib correctly truncates paragraphs and doesn't leave any stray tags for well-formed HTML. I even tested a few malformed variations and it worked like a champ. 🏆

Can't wait to see this get pushed. Do you have a donation link? 💰

**Comment by oe** [comment]
This package has been updated to `v0.1.4`. Enjoy!   
There is no need to donation to me, thank you.
