### ISSUE TITLE
Causes serious issue relating to unknown module "events" with NativeScript

### ISSUE THREAD

**Issue by nmandyam** [evecalm/truncate-html#15]
Used this with a NativeScript project. Caused a strange error relating to "module events not found in tns_modules". Took me some time to figure out that this module was the culprit. Removed it from my project, all OK.

**Comment by oe** [comment]
Do you use `npm install ` with `--save` option? Or it may be a problem with the only dependency `cheerio`.   NativeScript can not run every node packages, you may try [truncate](https://github.com/pathable/truncate) or [nodejs-html-truncate](https://github.com/huang47/nodejs-html-truncate) instead.

**Comment by calebeno** [comment]
@nmandyam which release version were you using?  If it was less than one of the 1.0.0-rc versions you probably had an issue with cheerio being an older version.  Once the 1.0.0 version is released it should have fixed that issue. Even if you don't use the library again could you reply back so we can ensure there isn't an issue if others pull it in?  Especially if you were using one of the release candidates.

**Comment by oe** [comment]
@nmandyam `truncate-html` has release a stable version `v1.0.0`, you may have a try. This issue will be closed. 
If you have any further questions, you may reply and reopen this issue.
