### ISSUE TITLE
Reuse existing cheerio instance, avoid reparsing

### ISSUE THREAD

**Issue by valpackett** [evecalm/truncate-html#18]
I'm already doing some processing using cheerio, and I'd like to truncate the result. Currently, truncate-html only accepts text and always invokes `cheerio.load`, so that's an extra HTML parse. Would be nice if I could truncate an existing cheerio `$`.

**Comment by oe** [comment]
Got it! I'll try to rewrite it will typescript and make it can handle existing cheerio.

**Comment by oe** [comment]
Hi @myfreeweb , I've added support for  **using existing cheerio instance**  just now, you may try it by `yarn add truncate-html@1.0.1-rc.1`. If nothing goes wrong, I'll make a public release.

**Comment by oe** [comment]
> If you want use existing cheerio instance, truncate option `decodeEntities` will not work, you should set it in your own cheerio instance:
```js
const $ = cheerio.load(`${html}`, {
  decodeEntities: true
  /** other cheerio options */
})
```
