### ISSUE TITLE
TypeError: $ is not a function

### ISSUE THREAD

**Issue by SteveMcArthur** [evecalm/truncate-html#2]
`$` is not yet assigned when html is object

line 54-59 of truncate.js

```
 if (typeof html === 'object') {
    html = $(html).html();
  }
  $ = cheerio.load("<div>" + html + "</div>", {
    decodeEntities: options.decodeEntities
  });
```

This happens to me when my html is actually null, so perhaps there should be a check somewhere for null as well as assigning the `$` var further up

**Comment by oe** [comment]
@SteveMcArthur There is already a check in line 51. Could you put your use case here?
