### ISSUE TITLE
Perversing the last word for a single word over the character limit

### ISSUE THREAD

**Issue by scdev0** [evecalm/truncate-html#23]
When the text is just a single word and we want to preserve it, it allows up to the character limit + 10 right now. Is there a way to make it just the character limit? The options I used to reproduce this is `{ length: limitLength, reserveLastWord: -1, ellipsis: '' }`. The `-1` is used in the general case that I want to cut off the last word over the limit.

**Comment by oe** [comment]
@scdev0 could you provide your invoking sample here?  I'm too busy to reply you in time, sorry for that

**Comment by scdev0** [comment]
@oe Np. For example, with `{length: 5, reserveLastWord: -1, ellipsis: '' }`,  `<p>12345678901234567890</p>` will get truncated to `<p>123456789012345</p>` instead of `<p>12345</p>`.

**Comment by oe** [comment]
This logic is made intentionally. I think it's  appropriate to reserve the only word when `reserveLastWord` is negative.   You may show me your usage scenario and tell me why you need this behaviour.

https://github.com/oe/truncate-html/blob/afe0222a2bfc15640e6354c859eff9e67c821010/src/truncate.ts#L215-L219

**Comment by scdev0** [comment]
But in the example it's not reserving the entire word also. It's cut off at 15 characters. So that's really confusing. If it's going to be truncated then the length should be what's set e.g. 5 in this case. I do want it to reserve the word if it's the only word but it should respect the length argument as well.

**Comment by oe** [comment]
I see, but  it can't reserve the whole word if the only word is super long. The max overflow length is set to 10 by default.  Check  L223-L226 for more details

https://github.com/oe/truncate-html/blob/964aeffd7e2feecccd841719538fa0650cfb5cd2/src/truncate.ts#L213-L229

**Comment by scdev0** [comment]
Yes I understand that. So I'm wondering if it's possible to make it so that the max overflow length is 0 in this case so that it's consistent with what I set the length to be i.e. 5 and not 5+10.

**Comment by oe** [comment]
if you want to reserve the whole world,  you should set the max overflow length , or just set  `reserveLastWord ` to `false`

**Comment by scdev0** [comment]
But setting `reserveLastWord` to `false` can get partial last word which I don't want. Basically, I need:
1. In the case there's more than one word, cut off the last word if cut in the middle i.e. `reserveLastWord` is `-1`
2. In the case the text is just one word, truncate it at the length I set e.g. 5 not 5+10
Are there any combination of options to give me both?

**Comment by oe** [comment]
@scdev0 I've added an option `trimTheOnlyWord`, set it to `true` with `reserveLastWord  = -1` to handle your situation.  It's not published yet, try yourself by checking out the `dist` folder.  I'll publish this version if this can fix your issue :)

**Comment by oe** [comment]
close due to inactive
