### ISSUE TITLE
Different behaviour when text is exactly at limit vs over limit when preversing last word

### ISSUE THREAD

**Issue by scdev0** [evecalm/truncate-html#24]
Using these options { length: 10, reserveLastWord: -1, ellipsis: '' }.
`<p>a b c d ef</p>` gets incorrectly truncated to `<p>a b c d</p>` whereas `<p>a b c d ef gh</p>` is correctly truncated to `<p>a b c d ef</p>`

**Comment by oe** [comment]
@scdev0 you may try to install v1.0.3 to fix this issue
