### ISSUE TITLE
Option to not remove extra white spaces

### ISSUE THREAD

**Issue by rolandleth** [evecalm/truncate-html#3]
It breaks `pre` blocks, by putting everything on a single line.

Would be nice to have this optional, at least. Solved by removing the `replace` call on line 84:

``` js
text = $(this).text().replace(/\s+/g, ' ');
```

Should I open a PR with it?

**Comment by oe** [comment]
Thanks for your feedback.
The source code is in coffeescript, it's OK if you can fix with it, or I will fix it later.

**Comment by rolandleth** [comment]
While it was rather easy to find where the replacing occurs, I don't really think I understand the logic enough to be sure I'm not breaking anything. I only tested a handful of use cases, for my particular project, so I'd rather not mess and break things. 

Thanks for the fast reply!

**Comment by oe** [comment]
A new option `keepWhitespaces` has been added, you may set it to `true` to keep whitespaces. `truncate-html` version has been updated to `v0.1.0`.  You can update now. Enjoy!

**Comment by oe** [comment]
@rolandleth My English name is **Saiya**, please fix it on your branch repo 🙏

**Comment by rolandleth** [comment]
I'm sorry 😵 I will take it down, anyway, I just needed something to deploy that night 🙂

Thanks for adding the feature, and for being so responsive! 🎉
