### ISSUE TITLE
High vulnerabie dependency found when installing the package

### ISSUE THREAD

**Issue by hfknight** [evecalm/truncate-html#31]
I received the message below when run 'npm install truncate-html@latest'
-------------------------------------------------------------------------------------
css-what  <5.0.1
Severity: high
Denial of Service - https://npmjs.com/advisories/1754
fix available via `npm audit fix --force`
Will install truncate-html@0.0.1, which is a breaking change
node_modules/cheerio/node_modules/css-what
  css-select  <=3.1.2
  Depends on vulnerable versions of css-what
  node_modules/cheerio/node_modules/css-select
    cheerio  0.19.0 - 1.0.0-rc.3
    Depends on vulnerable versions of css-select
    node_modules/cheerio
      truncate-html  >=0.0.2
      Depends on vulnerable versions of cheerio
      node_modules/truncate-html

**Comment by oe** [comment]
![image](https://user-images.githubusercontent.com/1655294/121523600-f9009680-ca28-11eb-83e8-b5957eec2102.png)

`css-what` is an indirect dependency of `cheerio`, which is the only dependency of `truncate-html`.
`truncate-html` is using `cheerio@0.22.0` by now, and  [`cheerio`'s latest version 1.0.0-rc.10](https://www.npmjs.com/package/cheerio) has removed `css-select`, that should fix this issue.

 I'll try to update to latest stable release of `cheerio` when it's officially available.
Thanks for your feedback.

**Comment by jmas** [comment]
<img width="772" alt="Screenshot 2022-12-12 at 01 50 33" src="https://user-images.githubusercontent.com/90701/206936390-3fec6631-194d-4737-abac-edb88df0f046.png">

**Comment by Zoha** [comment]
any updates @oe ?

**Comment by oe** [comment]
Sorry for the delay. [cheerio](https://www.npmjs.com/package/cheerio) is still in beta, I'll try to make a beta release based on its latest beta release in the next few days.

**Comment by ThomasFeuillatre** [comment]
Hey, any idea on when you'll release this version plz ?

**Comment by oe** [comment]
By this weekend, stay tuned

**Comment by oe** [comment]
I've just released a beta version, you guys can install it via `yarn add truncate-html@beta`

There are several changes:
1. no vulnerabilities 
![CleanShot 2023-06-17 at 20 37 48](https://github.com/oe/truncate-html/assets/1655294/ffbf1e42-7c42-49b7-bdc3-fd4f08b26139)
2. cheerio can now  handle CJK characters correctly
3. if you are using custom cheerio instance with this library, you should set the third parameter of `cheerio.load` to `false`  to get rid of extra wrappers, see [load](https://cheerio.js.org/docs/basics/loading#load) for details.
4. better support for typescript

check the  [update-cheerio](https://github.com/oe/truncate-html/tree/feat/update-cheerio) branch for code changes

**Comment by oe** [comment]
just released a stable version `v1.1.0`
