### ISSUE TITLE
Typo in distributed version

### ISSUE THREAD

**Issue by jwanner83** [evecalm/truncate-html#33]
While I was debugging, I spotted a small typo. 😉 

https://github.com/oe/truncate-html/blob/master/dist/truncate.es.js#L2
https://github.com/oe/truncate-html/blob/master/dist/truncate.cjs.js#L2

The source of the mistake is here: https://github.com/oe/truncate-html/blob/master/rollup.config.ts#L12

**Comment by oe** [comment]
Thanks for reporting😄 

I'll update npm package  after fixing #31
