### ISSUE TITLE
Depedency vulnerabilities

### ISSUE THREAD

**Issue by bensimian** [evecalm/truncate-html#35]
According to a few node vulnerability websites (snyk.io and nodesecurity.io), this package has a few vulnerabilities caused by the package nth-check. Is there any reason those haven't been updated yet? 
Thanks in advance

**Comment by oe** [comment]
same reason as #31 
![CleanShot 2022-06-19 at 12 35 07](https://user-images.githubusercontent.com/1655294/174466006-64c3a975-9d7a-4a73-bad2-e70b6fa3466d.png)

I'll fix it when cheerio release the next stable version
