### ISSUE TITLE
Console.logs

### ISSUE THREAD

**Issue by rolandleth** [evecalm/truncate-html#4]
Hey,

on lines `100` and `101` (`91` and `92` in `.coffee`) you forgot console.log statements :)

``` js
console.log($1 + ' ~~~ ' + $2);
console.log($1.length + ' ~~~ ' + $2.length);
```

**Comment by oe** [comment]
😓 Sorry for that, `console.log` statements have been removed. Package version has been updated to v0.1.1

**Comment by rolandleth** [comment]
Thank you!
