### ISSUE TITLE
stripTags: true does not strip tags

### ISSUE THREAD

**Issue by medv** [evecalm/truncate-html#6]
```
truncate('<p>some text here</p>', 3, { stripTags: true })
>> '<p>som...</p>'
```

**Comment by oe** [comment]
What version are you using?

I tested your case with the latest version(v0.1.4), works fine.

**Comment by medv** [comment]
This is actually probably the stupidest thing I've posted. I installed html-truncate and came in here complaining that your api doesn't work for another package.

```
"html-truncate": {
  "version": "1.2.2",
  "resolved": "https://registry.npmjs.org/html-truncate/-/html-truncate-1.2.2.tgz",
  "integrity": "sha1-2y4zHc8cugvUMqUH0W6YhgnyV18="
},
```

Happy new year.

**Comment by oe** [comment]
😄  You may try my package, it works fine with nodejs. I've tried `html-truncate` before, but it can't meet my need(cannot exclude specified tags), so I created this project.
