### ISSUE TITLE
Feature request: add option to truncate at word boundary

### ISSUE THREAD

**Issue by baseten** [evecalm/truncate-html#7]
When truncating by character count, it would be useful to have an option so that if the text is cut in the middle of a word it either add or removes the whole word, rather than cutting in the middle.

**Comment by oe** [comment]
This feature may only work in alphabet languages. I'll consider about it.

**Comment by oe** [comment]
@baseten you can try this feature by install the latest version `npm install truncate-html@1.0.0-rc.3 `, a new options `reserveLastWord ` is available,  see [API](https://github.com/evecalm/truncate-html#api) for details
