### ISSUE TITLE
Option for add space after end of tag

### ISSUE THREAD

**Issue by isuke01** [evecalm/truncate-html#8]
There is a issue when you got text like `<p>some text</p><p>Hello World</p>` 
you will get output: `some textHello World`, 
As you can see without space between **text** and **hello**
Ofc. easy fix is to regex add space after closing tag if there is no space, but it would be nice it this can do it for me.

**Comment by oe** [comment]
good point, I'll try

**Comment by oe** [comment]
I've considered about this, I think this maybe a false request, if the html is well formatted, this problem won't exist. So you may use regex to make a workaround.
